{{- if not (lookup "v1" "Secret" .Release.Namespace .Values.config.auth.passwordSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.auth.passwordSecret }}
  labels:
    {{- include "parachute.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ "changeme" | b64enc | quote }}
{{- end }}
